version: '3.1'

services:
  app:
    build: .
    ports:
      - 8080:8080
    environment:    
      DATASOURCE_URL: jdbc:mysql://db:3306/adopet
      DATASOURCE_USERNAME: root
      DATASOURCE_PASSWORD: pass
    depends_on:
      - db
  db:
    image: mysql
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: pass
    volumes:
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql



